"""
EDV Jr. - Biblioteca Curada de Micro-Entregáveis (Atomic Learning Blocks)
Catálogo oficial de micro-ações isoladas tagueadas por competência da Brasil Júnior,
eixo (Hard/Soft Skills), complexidade e nível hierárquico para o EDbrain.
"""

INITIAL_LEARNING_MICROBLOCKS = [
    # =========================================================================
    # LIDERANÇA (Mobilização, feedback, cultura e sucessão)
    # =========================================================================
    (
        "MB-LID-401",
        "Condução de Feedback Cruzado 1-on-1 Estruturado",
        "lideranca",
        "soft_skills",
        "Cross-Setorial",
        "todos",
        1,
        "Realização de sessão de feedback bilateral utilizando a metodologia SCI (Situação-Comportamento-Impacto) com geração de plano de ação mútuo.",
        "Registro Formal de Feedback 1-on-1",
        5,
        15,
        "feedback, sci, 1-on-1, empatia, escuta ativa, liderança"
    ),
    (
        "MB-LID-402",
        "Facilitação de Reunião Geral da EJ (Ágora EDV)",
        "lideranca",
        "soft_skills",
        "Presidência",
        "diretor",
        2,
        "Planejamento de pauta, facilitação e alinhamento de engajamento do time na reunião semanal da EJ com dinâmica de check-in e check-out.",
        "Ata e Gravação de Reunião",
        8,
        20,
        "ágora, facilitação, engajamento, oratória, liderança"
    ),
    (
        "MB-LID-403",
        "Formação e Mentoria de Sucessor de Área",
        "lideranca",
        "soft_skills",
        "Cross-Setorial",
        "diretor",
        3,
        "Estruturação de trilha de transição de cargo, shadowing prático e repasse de processos críticos para o plano sucessório institucional.",
        "Dossiê de Transição de Gestão",
        20,
        60,
        "sucessão, mentoria, transição, governança, liderança"
    ),
    (
        "MB-LID-404",
        "Mediação de Conflitos e Alinhamento de Expectativas",
        "lideranca",
        "soft_skills",
        "VPGG",
        "todos",
        2,
        "Condução de conversa de alinhamento com metodologia de Comunicação Não-Violenta (CNV) entre integrantes de projeto para redefinir papéis.",
        "Termo de Acordo de Convivência",
        6,
        15,
        "cnv, conflito, alinhamento, clima, mediação"
    ),
    (
        "MB-LID-405",
        "Delegação Eficaz com Matriz de Autonomia",
        "lideranca",
        "soft_skills",
        "Cross-Setorial",
        "gerente",
        2,
        "Mapeamento das tarefas da equipe e aplicação dos 7 níveis de delegação para empoderamento dos assessores com checkpoints claros.",
        "Matriz de Delegação Preenchida",
        8,
        30,
        "delegação, autonomia, liderança tática, gestão de equipe"
    ),
    (
        "MB-LID-406",
        "Onboarding e Acolhimento de Trainees",
        "lideranca",
        "soft_skills",
        "VPGG",
        "assessor",
        1,
        "Acompanhamento direto e tutoria de 2 novos membros no período de integração à cultura da EDV Jr.",
        "Checklist de Onboarding Concluído",
        10,
        30,
        "onboarding, cultura, acolhimento, trainee, integração"
    ),
    (
        "MB-LID-407",
        "Condução de Retrospectiva Ágil de Equipe",
        "lideranca",
        "soft_skills",
        "Projetos",
        "gerente",
        2,
        "Facilitação de cerimônia ágil (Mad/Sad/Glad) com identificação de melhorias contínuas no fluxo de trabalho.",
        "Quadro de Ações da Retrospectiva",
        6,
        15,
        "ágil, retrospectiva, melhoria contínua, rito, time"
    ),
    (
        "MB-LID-408",
        "Gestão de Crise e Alinhamento Institucional",
        "lideranca",
        "soft_skills",
        "Presidência",
        "presidente",
        3,
        "Comunicação transparente com partes interessadas em momento de atraso crítico ou impasse regulatório, preservando a reputação da EJ.",
        "Comunicado Oficial e Plano de Contingência",
        12,
        10,
        "crise, contingência, comunicação executiva, liderança"
    ),

    # =========================================================================
    # GESTÃO (Processos, prazos, rigor metodológico, SLA e rotina)
    # =========================================================================
    (
        "MB-GES-811",
        "Análise de DRE Gerencial e Apuração de Margem",
        "gestao",
        "hard_skills",
        "Tesouraria",
        "todos",
        2,
        "Elaboração do Demonstrativo de Resultados do Exercício discriminando receitas por serviço e despesas operacionais da EJ.",
        "Planilha de DRE Consolidada",
        10,
        30,
        "dre, financeiro, margem, resultado, custos"
    ),
    (
        "MB-GES-812",
        "Auditoria de Prazos Fatais e Despachos do INPI",
        "gestao",
        "hard_skills",
        "Projetos",
        "assessor",
        1,
        "Varredura semanal dos despachos da Revista da Propriedade Industrial (RPI) para marcas em carteira, garantindo 0 perdas de prazos.",
        "Relatório Semanal de Despachos RPI",
        12,
        20,
        "inpi, rpi, prazos fatais, processo de marcas, rigor"
    ),
    (
        "MB-GES-813",
        "Revisão e Otimização de POP Operacional",
        "gestao",
        "hard_skills",
        "Projetos",
        "gerente",
        2,
        "Mapeamento das etapas de depósito de marca e atualização do Procedimento Operacional Padrão eliminando gargalos de execução.",
        "POP Revisado e Homologado",
        15,
        45,
        "pop, processos, melhoria contínua, padronização, eficiência"
    ),
    (
        "MB-GES-814",
        "Alinhamento e Gestão de SLA Comercial",
        "gestao",
        "hard_skills",
        "Comercial",
        "assessor",
        1,
        "Controle diário do tempo de resposta a leads inbound no CRM para manter o tempo médio de primeira abordagem abaixo de 2 horas.",
        "Dashboard de Tempo de Resposta de Leads",
        8,
        20,
        "sla, tempo de resposta, crm, disciplina, cadência"
    ),
    (
        "MB-GES-815",
        "Orçamento Base Zero (OBZ) e Projeção de Caixa",
        "gestao",
        "hard_skills",
        "Tesouraria",
        "diretor",
        3,
        "Construção da projeção orçamentária trimestral com justificativa individual de cada centro de custo sob a ótica do OBZ.",
        "Modelo de OBZ Trimestral",
        16,
        45,
        "obz, fluxo de caixa, orçamento, tesouraria, controle"
    ),
    (
        "MB-GES-816",
        "Gestão de Backlog e Priorização Eisenhower",
        "gestao",
        "soft_skills",
        "Cross-Setorial",
        "todos",
        1,
        "Classificação semanal de tarefas em Urgente vs Importante para blindagem de tempo e cumprimento de entregáveis prioritários.",
        "Quadro Kanban Priorizado",
        6,
        15,
        "eisenhower, priorização, gestão do tempo, kanban, rotina"
    ),
    (
        "MB-GES-817",
        "Conciliação Bancária e Controle de Inadimplência",
        "gestao",
        "hard_skills",
        "Tesouraria",
        "assessor",
        2,
        "Cruzamento diário dos extratos da conta Cora com os lançamentos de honorários de marcas e envio de lembretes preventivos.",
        "Planilha de Conciliação e Régua de Cobrança",
        10,
        30,
        "conciliação, cobrança, fluxo financeiro, rigor, pontualidade"
    ),
    (
        "MB-GES-818",
        "Estruturação de OKRs de Diretoria",
        "gestao",
        "hard_skills",
        "Presidência",
        "diretor",
        3,
        "Definição de 3 Objetivos e 4 Resultados-Chave trimestrais para alinhamento das metas táticas com a estratégia geral da EJ.",
        "Matriz de OKRs Trimestral",
        12,
        30,
        "okr, metas, kpi, planejamento tático, gestão por resultados"
    ),

    # =========================================================================
    # ORIENTAÇÃO PARA RESULTADOS (Vendas, propostas, metas e conversão)
    # =========================================================================
    (
        "MB-COM-101",
        "Qualificação de Leads B2B via SPIN Selling",
        "orientacao_resultados",
        "hard_skills",
        "Comercial",
        "assessor",
        2,
        "Aplicação de roteiro estruturado de perguntas de Situação, Problema, Implicação e Necessidade de Solução em 5 reuniões de diagnóstico.",
        "Gravação e Ficha de Diagnóstico SPIN",
        12,
        30,
        "spin selling, vendas, diagnóstico, comercial, qualificação"
    ),
    (
        "MB-COM-102",
        "Elaboração de Proposta Comercial de Alto Valor",
        "orientacao_resultados",
        "hard_skills",
        "Comercial",
        "todos",
        2,
        "Redação de proposta personalizada de registro de marcas destacando o ROI da proteção contra cópia e pirataria industrial.",
        "Proposta Comercial Emitida e Protocolada",
        8,
        20,
        "proposta, precificação, valor percebido, negociação, comercial"
    ),
    (
        "MB-COM-103",
        "Mapeamento e Prospecção Ativa via Radar",
        "orientacao_resultados",
        "hard_skills",
        "Comercial",
        "assessor",
        1,
        "Triagem e abordagem ativa de 20 empresas de médio porte no Espírito Santo sem registro de marca no INPI.",
        "Planilha de Prospecção Ativa Atualizada",
        15,
        30,
        "radar, outbound, prospecção ativa, cold mail, b2b"
    ),
    (
        "MB-COM-104",
        "Contorno Consultivo de Objeções de Preço",
        "orientacao_resultados",
        "soft_skills",
        "Comercial",
        "todos",
        2,
        "Simulação e aplicação prática de argumentos éticos de ancoragem de valor para converter clientes reticentes em relação a taxas oficiais do INPI.",
        "Matriz de Objeções e Pitch Gravado",
        8,
        20,
        "objeções, persuasão ética, negociação, fechamento"
    ),
    (
        "MB-COM-105",
        "Triagem Rápida de CNPJs na Receita via BrasilAPI",
        "orientacao_resultados",
        "hard_skills",
        "Comercial",
        "assessor",
        1,
        "Consulta e validação cadastral e de CNAE de potenciais clientes para verificação prévia de viabilidade de enquadramento societário.",
        "Dossiê de Qualificação Fiscal de Leads",
        6,
        15,
        "brasilapi, cnpj, qualificação cadastral, compliance fiscal"
    ),
    (
        "MB-COM-106",
        "Fechamento de Contrato com Gatilho de Urgência Ética",
        "orientacao_resultados",
        "hard_skills",
        "Comercial",
        "assessor",
        3,
        "Condução de fechamento de contrato de marcas enfatizando o princípio da anterioridade ('quem registra primeiro é dono').",
        "Contrato Assinado no CRM",
        10,
        30,
        "fechamento, contrato, anterioridade, conversão, receita"
    ),
    (
        "MB-COM-107",
        "Criação de Campanha Inbound com Foco em Leads Qualificados",
        "orientacao_resultados",
        "hard_skills",
        "Marketing",
        "assessor",
        2,
        "Planejamento e publicação de série de 3 conteúdos educativos que gerem no mínimo 10 conversões orgânicas para o CRM.",
        "Relatório de Leads Inbound Gerados",
        14,
        30,
        "inbound marketing, geração de leads, conversão, métricas"
    ),
    (
        "MB-COM-108",
        "Atingimento de Meta de Faturamento Mensal",
        "orientacao_resultados",
        "hard_skills",
        "Comercial",
        "diretor",
        3,
        "Monitoramento da esteira de vendas para garantir a conversão mínima de R$ 10.000 em propostas fechadas no ciclo.",
        "Relatório de Cumprimento de Meta Comercial",
        20,
        30,
        "faturamento, meta, alta performance, receita, pipeline"
    ),

    # =========================================================================
    # GESTÃO & PROJETOS TÉCNICOS (Marcas, INPI e Operações)
    # =========================================================================
    (
        "MB-PRJ-201",
        "Busca de Anterioridade Fonética e Figurativa no INPI",
        "gestao",
        "hard_skills",
        "Projetos",
        "assessor",
        1,
        "Execução de pesquisa prévia na base do INPI nas classes de Nice pertinentes com emissão de parecer de viabilidade registrária.",
        "Parecer de Viabilidade de Registro de Marca",
        10,
        20,
        "inpi, busca prévia, anterioridade, classe de nice, marca"
    ),
    (
        "MB-PRJ-202",
        "Elaboração de Peça de Oposição a Registro de Marca",
        "gestao",
        "hard_skills",
        "Projetos",
        "assessor",
        2,
        "Redação fundamentada de petição de oposição contra marca colidente protocolada por terceiro, nos termos do Art. 124 da LPI.",
        "Minuta de Oposição com Protocolo INPI",
        14,
        30,
        "oposição, lpi, colidência de marcas, defesa administrativa"
    ),
    (
        "MB-PRJ-203",
        "Interposição de Recurso contra Indeferimento do INPI",
        "gestao",
        "hard_skills",
        "Projetos",
        "gerente",
        3,
        "Construção de tese recursal contra decisão desfavorável de examinador do INPI fundamentada em distintividade e especialidade.",
        "Recurso Administrativo Protocolado",
        16,
        45,
        "recurso, indeferimento, inpi, distintividade, marcas"
    ),
    (
        "MB-PRJ-204",
        "Gestão de Carteira e Cadência de Notificações a Clientes",
        "gestao",
        "hard_skills",
        "Projetos",
        "assessor",
        1,
        "Atualização de status e envio de notificações formais a 10 clientes sobre o andamento de seus processos de marcas.",
        "Relatório de Contatos e Notificações aos Clientes",
        8,
        20,
        "atendimento, carteira de clientes, fidelização, transparência"
    ),

    # =========================================================================
    # VISÃO SISTÊMICA (Ecossistema MEJ, Selo EJ, Conformidade e Estratégia)
    # =========================================================================
    (
        "MB-VIS-901",
        "Auditoria de Conformidade com o Selo EJ 2026",
        "visao_sistemica",
        "hard_skills",
        "Jurídico",
        "todos",
        2,
        "Revisão dos 7 critérios federais e federativos (RAIS, CNDs, Estatuto, RPDA) garantindo 100% de conformidade com a Brasil Júnior.",
        "Checklist do Selo EJ Homologado",
        12,
        30,
        "selo ej, brasil júnior, conformidade, governança, rais, cnd"
    ),
    (
        "MB-VIS-902",
        "Adequação de Políticas Internas à LGPD",
        "visao_sistemica",
        "hard_skills",
        "Jurídico",
        "assessor",
        2,
        "Elaboração de termo de consentimento e mapeamento de fluxo de dados de leads comerciais para conformidade com a Lei 13.709/2018.",
        "Política de Privacidade e Termo LGPD",
        10,
        30,
        "lgpd, privacidade de dados, conformidade, jurídico"
    ),
    (
        "MB-VIS-903",
        "Análise de Alinhamento com o PE 25-27 da Brasil Júnior",
        "visao_sistemica",
        "soft_skills",
        "Presidência",
        "diretor",
        3,
        "Diagnóstico da contribuição da EDV Jr. para as metas de Alto Impacto e Diversidade da Federação no ciclo estratégico.",
        "Painel de Conexão Estratégica MEJ",
        15,
        45,
        "pe brasil júnior, alto impacto, federação, estratégia"
    ),
    (
        "MB-VIS-904",
        "Benchmarking com EJ de Referência Nacional",
        "visao_sistemica",
        "soft_skills",
        "Cross-Setorial",
        "todos",
        2,
        "Condução de reunião de intercâmbio de boas práticas com EJ líder em vendas ou marcas para captação de inovações de processo.",
        "Apresentação de Benchmarking na Ágora",
        10,
        30,
        "benchmarking, inovação, ecossistema, melhores práticas"
    ),
    (
        "MB-VIS-905",
        "Integração Intersetorial Comercial-Projetos-Jurídico",
        "visao_sistemica",
        "soft_skills",
        "Cross-Setorial",
        "gerente",
        2,
        "Criação de fluxo conjunto de validação rápida de viabilidade de marca antes do envio de proposta comercial.",
        "Fluxograma de Validação Prévia Implementado",
        8,
        20,
        "intersetorial, fluxo de trabalho, visão integrada, colaboração"
    ),
    (
        "MB-VIS-906",
        "Participação e Representação em Eventos do MEJ (ENEJ/Capixaba)",
        "visao_sistemica",
        "soft_skills",
        "Presidência",
        "todos",
        1,
        "Representação oficial da empresa, networking estratégico e compartilhamento dos aprendizados com a equipe interna.",
        "Relatório de Insights e Conexões do Evento",
        8,
        20,
        "enej, fejemg, mej capixaba, representação institucional"
    ),

    # =========================================================================
    # AUTOCONHECIMENTO (Reflexão, inteligência emocional e feedback)
    # =========================================================================
    (
        "MB-AUT-301",
        "Diário de Bordo de Liderança e Autoavaliação Reflexiva",
        "autoconhecimento",
        "soft_skills",
        "Cross-Setorial",
        "todos",
        1,
        "Registro semanal de tomadas de decisão, pontos de tensão emocional e aprendizados comportamentais com reflexão estruturada.",
        "Diário de Bordo Trimestral Consolidado",
        8,
        45,
        "diário de bordo, reflexão, autoconhecimento, inteligência emocional"
    ),
    (
        "MB-AUT-302",
        "Inteligência Emocional sob Pressão de Prazos",
        "autoconhecimento",
        "soft_skills",
        "Cross-Setorial",
        "todos",
        2,
        "Aplicação de técnicas de regulação emocional e escuta ativa durante momentos de alta demanda operacional ou objeções difíceis.",
        "Autoavaliação de Gestão de Stress",
        6,
        30,
        "inteligência emocional, resiliência, auto-regulação, maturidade"
    ),
    (
        "MB-AUT-303",
        "Mapeamento de Pontos Fortes e Oportunidades (Matriz SWOT Pessoal)",
        "autoconhecimento",
        "soft_skills",
        "VPGG",
        "todos",
        1,
        "Construção de diagnóstico individual de fortalezas técnicas, limitações comportamentais e plano de capacitação focado.",
        "Matriz SWOT Pessoal Validada pela VPGG",
        6,
        15,
        "swot pessoal, pontos fortes, autodesenvolvimento, diagnóstico"
    ),
    (
        "MB-AUT-304",
        "Prática Intensiva de Escuta Ativa em Reuniões",
        "autoconhecimento",
        "soft_skills",
        "Cross-Setorial",
        "todos",
        1,
        "Exercício deliberado de não-interrupção e paráfrase compreensiva nas interações de equipe durante um mês de gestão.",
        "Registro Reflexivo de Interações",
        5,
        30,
        "escuta ativa, empatia, diálogo, comunicação interpessoal"
    ),
    (
        "MB-AUT-305",
        "Ciclo de Mentoria Reversa com Membros Trainees",
        "autoconhecimento",
        "soft_skills",
        "Cross-Setorial",
        "diretor",
        2,
        "Abertura para receber feedbacks e percepções francas de assessores novatos sobre a comunicação e clareza da liderança.",
        "Síntese de Aprendizados da Mentoria Reversa",
        6,
        30,
        "mentoria reversa, humildade intelectual, vulnerabilidade, liderança servidora"
    ),
    (
        "MB-AUT-306",
        "Equilíbrio entre Vida Pessoal e Rotina Institucional",
        "autoconhecimento",
        "soft_skills",
        "Cross-Setorial",
        "todos",
        1,
        "Definição de limites claros de disponibilidade, pausas produtivas e organização da semana para prevenção de burnout.",
        "Plano de Sustentabilidade Pessoal de Gestão",
        5,
        20,
        "equilíbrio, gestão do tempo, saúde mental, sustentabilidade pessoal"
    ),

    # =========================================================================
    # ÁREAS ESPECÍFICAS (Jurídico, Marketing, Tesouraria, Formação de Avaliadores)
    # =========================================================================
    (
        "MB-JUR-601",
        "Elaboração de Minuta de Contrato de Parceria Estratégica",
        "visao_sistemica",
        "hard_skills",
        "Jurídico",
        "assessor",
        2,
        "Redação de instrumento contratual de cooperação técnica e institucional com universidade ou entidade do ecossistema.",
        "Minuta Contratual Chancelada",
        12,
        30,
        "contrato, parceria, jurídico, minuta, cooperação"
    ),
    (
        "MB-JUR-602",
        "Análise de Riscos e Compliance de Marca",
        "gestao",
        "hard_skills",
        "Jurídico",
        "assessor",
        2,
        "Parecer jurídico analítico sobre riscos de colidência com marcas notórias ou de alto renome segundo o Art. 125/126 da LPI.",
        "Parecer de Risco Marcário",
        10,
        20,
        "marcas notórias, alto renome, risco, parecer jurídico"
    ),
    (
        "MB-MKT-701",
        "Criação de Linha Editorial Educativa sobre Proteção de Marcas",
        "orientacao_resultados",
        "hard_skills",
        "Marketing",
        "assessor",
        1,
        "Desenvolvimento de roteiros de 4 posts para o Instagram explicando a diferença entre razão social, nome fantasia e marca registrada.",
        "Calendário Editorial e Roteiros Homologados",
        10,
        20,
        "marketing jurídico, conteúdo educativo, branding, marcas"
    ),
    (
        "MB-MKT-702",
        "Otimização de Copywriting de Conversão para Propostas",
        "orientacao_resultados",
        "hard_skills",
        "Marketing",
        "assessor",
        2,
        "Revisão dos textos e gatilhos de fechamento dos materiais de apresentação comercial da EDV Jr.",
        "Kit de Copywriting Comercial Revisado",
        8,
        15,
        "copywriting, persuasão, conversão, materiais comerciais"
    ),
    (
        "MB-MKT-703",
        "Análise de Tráfego e Taxa de Engajamento de Campanhas",
        "orientacao_resultados",
        "hard_skills",
        "Marketing",
        "assessor",
        2,
        "Mensuração de impressões, cliques e conversões de leads gerados pelas campanhas de captação digital da EJ.",
        "Dashboard de Métricas de Marketing",
        10,
        30,
        "métricas, tráfego, engajamento, conversão, marketing"
    ),
    (
        "MB-FIN-501",
        "Criação de Simulador de Precificação de Honorários de Marcas",
        "orientacao_resultados",
        "hard_skills",
        "Tesouraria",
        "assessor",
        2,
        "Desenvolvimento de calculadora de preços com base em custos fixos, horas dedicadas e margem de contribuição mínima da EJ.",
        "Planilha de Precificação Parametrizada",
        12,
        30,
        "precificação, simulador, finanças, margem de contribuição"
    ),
    (
        "MB-FIN-502",
        "Prestação de Contas Trimestral para Assembleia Geral",
        "visao_sistemica",
        "hard_skills",
        "Tesouraria",
        "diretor",
        3,
        "Consolidação e apresentação transparente das entradas, saídas, patrimônio líquido e saúde financeira para os membros da EJ.",
        "Apresentação e Parecer Fiscal para AG",
        15,
        45,
        "prestação de contas, assembleia geral, transparência, finanças"
    ),
    (
        "MB-LID-409",
        "Formação de Novos Avaliadores para o Ciclo de Avaliação 360º",
        "lideranca",
        "soft_skills",
        "VPGG",
        "diretor",
        2,
        "Oficina prática para orientar membros sobre como fornecer feedbacks construtivos sem viés de benevolência ou severidade.",
        "Oficina Ministrada e Guia de Calibração",
        8,
        20,
        "avaliação 360, calibração de avaliadores, feedback, vpgg"
    )
]
